vulnerabilities:
  - id: CVE-2024-12797
    expired_at: 2025-03-31
    statement: BaseImage CVE, not fixable

misconfigurations:
  - id: KSV011
    statement: CPU and RAM not limited - They are configured in the Stage Configuration
  - id: KSV015
    statement: CPU and RAM not limited - They are configured in the Stage Configuration
  - id: KSV016
    statement: CPU and RAM not limited - They are configured in the Stage Configuration
  - id: KSV018
    statement: CPU and RAM not limited - They are configured in the Stage Configuration
  - id: KSV020
    statement: Runs with UID <= 10000 - User is 10000 in Dockerfile too
  - id: KSV021
    statement: Runs with UID <= 10000 - User is 10000 in Dockerfile too
  - id: KSV027
    statement: Non-default /proc masks set - Not detected by Trivy

# Ignore single packages is temporarily not supported
licenses:
  - id: GPL-2.0-only
  - id: GPL-2.0-or-later
  - id: LGPL-2.1-or-later
  - id: MPL-2.0
  - id: GPL-2.0-with-classpath-exception