<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>de.gematik.demis</groupId>
    <artifactId>spring-parent</artifactId>
    <version>4.1.8</version>
    <relativePath></relativePath><!-- lookup parent from repository -->
  </parent>
  <artifactId>report-processing-service</artifactId>
  <version>2.4.1-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>report-processing-service</name>
  <description>Processing service for report notifications for DEMIS</description>
  <licenses>
    <license>
      <name>Licensed under the EUPL 1.2</name>
      <url>https://joinup.ec.europa.eu/collection/eupl/eupl-text-eupl-12</url>
    </license>
  </licenses>
  <properties>
    <sonar.exclusions>**/de/gematik/demis/reportprocessingservice/ReportProcessingServiceApplication.java,
            **/de/gematik/demis/reportprocessingservice/exceptions/ParsingException.java</sonar.exclusions>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.codehaus.woodstox</groupId>
        <artifactId>stax2-api</artifactId>
        <version>4.2.2</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>de.gematik.demis</groupId>
      <artifactId>notification-builder-library</artifactId>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcpkix-jdk18on</artifactId>
    </dependency>
    <dependency>
      <groupId>org.bouncycastle</groupId>
      <artifactId>bcprov-jdk18on</artifactId>
    </dependency>
    <dependency>
      <groupId>tools.jackson.dataformat</groupId>
      <artifactId>jackson-dataformat-xml</artifactId>
    </dependency>
    <dependency>
      <groupId>de.gematik.demis</groupId>
      <artifactId>spring-parent</artifactId>
      <classifier>tests</classifier>
      <type>test-jar</type>
      <version>${project.parent.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
